### ISSUE TITLE
Tests do not pass on skeleton

### ISSUE THREAD

**Issue by mdv5** [Dev-Ops-2021-Customers/customers#11]
When running nosetests on the skeleton project, the nosetests are not passing

**STEPS TO REPRODUCE**

1. Pull the skeleton branch from ``git checkout main`` followed by ``git pull``
2. Move to the skeleton branch ``git checkout skeleton``
3. ``Vagrant up``
4. ``Vagrant ssh``
5. ``cd /vagrant/``
6. ``nosetests``

**EXPECTED RESULT**
2 tests would show as passing, 0 fails

**OBSERVED RESULT**
Tests failed with 2 errors - Message below

E.E
======================================================================
ERROR: Failure: ImportError (cannot import name 'routes' from partially initialized module 'service' (most likely due to a circular import) (/vagrant/service/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/vagrant/service/__init__.py", line 17, in <module>
    from service import routes, models
ImportError: cannot import name 'routes' from partially initialized module 'service' (most likely due to a circular import) (/vagrant/service/__init__.py)

======================================================================
ERROR: Failure: ImportError (cannot import name 'routes' from partially initialized module 'service' (most likely due to a circular import) (/vagrant/service/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/vagrant/tests/test_service.py", line 14, in <module>
    from service.routes import app, init_db
  File "/vagrant/service/__init__.py", line 17, in <module>
    from service import routes, models
ImportError: cannot import name 'routes' from partially initialized module 'service' (most likely due to a circular import) (/vagrant/service/__init__.py)

----------------------------------------------------------------------
Ran 3 tests in 0.121s

FAILED (errors=2)

**Comment by mdv5** [comment]
After further investigation, I found that those errors were being caused because by the change in file name from routes.py to service.py. Changing it back to routes.py, fixes this error and uncovers a new one.
EEE
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (service.py, line 41))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/vagrant/service/__init__.py", line 17, in <module>
    from service import service, models
  File "/vagrant/service/service.py", line 41
    def init_db():
    ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (service.py, line 41))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/vagrant/tests/test_models.py", line 8, in <module>
    from service.models import YourResourceModel, DataValidationError, db
  File "/vagrant/service/__init__.py", line 17, in <module>
    from service import service, models
  File "/vagrant/service/service.py", line 41
    def init_db():
    ^
SyntaxError: invalid syntax

======================================================================
ERROR: Failure: SyntaxError (invalid syntax (service.py, line 41))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/venv/lib/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/vagrant/tests/test_service.py", line 13, in <module>
    from service.models import db
  File "/vagrant/service/__init__.py", line 17, in <module>
    from service import service, models
  File "/vagrant/service/service.py", line 41
    def init_db():
    ^
SyntaxError: invalid syntax

----------------------------------------------------------------------
Ran 3 tests in 0.093s

FAILED (errors=3)

**Comment by mdv5** [comment]
After investigating this issue I found that there were 2 issues happening here:
1. The issue being thrown was not actually on line 41 of service.py (which should be changed to routes.py). It is occurring due to a missing ) in the previous section, therefore it was being treated as part of the ``return`` for def index(). 

Adding ``),`` before status.HTTP_200_OK, fixes this issue, but once again uncovers a new one. 

2. This entire return statement is trying to point to a route we did not create yet. 

Therefore the working fix that solves both of these issues is:

@app.route("/")
def index():
    """ Root URL response """
    return (
        "Reminder: return some useful information in json format about the service here",
        status.HTTP_200_OK,
    )

**Comment by mdv5** [comment]
After investigating this issue I found that we had not changed YourResourceModel to Customer throughout the project. After doing a Find & Replace (make sure its set to case sensitive), the issue is resolved.
find: YourResourceModel
replace: Customer

Run ``nosetests`` and they now should pass.
